[package]
name = "metropolis"
version = "0.1.0"
authors = ["Lucas Javaudin <lucas@lucasjavaudin.com>"]
edition = "2021"
description = "A dynamic multi-modal traffic-assignment simulator"
repository = "https://git.lucasjavaudin.com/LucasJavaudin/metrolib"
keywords = ["transportation", "simulation", "traffic-assignment", "public-transit"]
categories = ["science", "simulation"]
publish = false

[workspace]

[dependencies]
choice = { path = "choice/" }
ttf = { path = "ttf/" }
tch = { path = "tch/" }
anyhow = "1.0"
askama = { version = "0.11", features = ["serde-json"] }
chrono = "0.4"
clap = { version = "3.1", features = ["derive"] }
env_logger = "0.9"
hashbrown = { version = "0.12", features = ["rayon"] }
indicatif = "0.16"
itertools = "0.10"
jemallocator = "0.5"
jemalloc-ctl = "0.5"
log = "0.4"
num-traits = "0.2"
object-pool = "0.5"
petgraph = { version = "0.6", default-features = false }
rand = "0.8"
rand_xorshift = "0.3"
rayon = "1.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
schemars = "0.8.7"
