[package]
name = "tch"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
petgraph = "0.6"
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
either = "1.6"
hashbrown = { version = "0.12", features = ["rayon"] }
priority-queue = "1.2"
fixedbitset = "0.4"
ordered-float = "2.10"
rayon = "1.5"
object-pool = "0.5"
geojson = "0.22"
csv = "1.1"
ttf = { path = "../ttf/", features = ["serde-1"] }

[features]
default = ["serde-1"]
serde-1 = ["serde", "serde_derive", "serde_json", "hashbrown/serde", "petgraph/serde-1", "ordered-float/serde"]
