[package]
name = "tch"
version = "0.1.0"
authors = ["Lucas Javaudin <me@lucasjavaudin.com>"]
edition = "2021"
description = "Time-dependent contraction hierarchies"
repository = "https://git.lucasjavaudin.com/LucasJavaudin/metrolib"
keywords = ["contraction-hierarchies", "routing", "shortest-path", "time-dependent", "graph"]
categories = ["algorithms"]
publish = false

[dependencies]
ttf = { path = "../ttf/" }
anyhow = "1.0"
bincode = "1.3"
csv = "1.1"
either = "1.6"
fixedbitset = "0.4"
geojson = "0.22"
hashbrown = { version = "0.12", features = ["rayon"] }
indicatif = "0.16"
log = "0.4"
petgraph = { version = "0.6", default-features = false, features = ["serde-1"] }
priority-queue = "1.2"
object-pool = "0.5"
ordered-float = { version = "2.10", features = ["serde"] }
rayon = "1.5"
serde = "1.0"
serde_json = "1.0"
schemars = "0.8"
