[package]
name = "tch"
version = "0.1.0"
edition = "2021"

[dependencies]
ttf = { path = "../ttf/", features = ["serde-1"] }
anyhow = "1.0"
bincode = "1.3"
csv = "1.1"
either = "1.6"
fixedbitset = "0.4"
geojson = "0.22"
hashbrown = { version = "0.12", features = ["rayon"] }
log = "0.4"
petgraph = "0.6"
priority-queue = "1.2"
object-pool = "0.5"
ordered-float = "2.10"
rayon = "1.5"
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }

[features]
default = ["serde-1"]
serde-1 = ["serde", "serde_derive", "serde_json", "hashbrown/serde", "petgraph/serde-1", "ordered-float/serde"]
