[package]
name = "choice"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
num-traits = "0.2"
breakpoint_function = { path = "../breakpoint_function" }
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }

[features]
serde-1 = ["serde", "serde_derive"]
