[package]
name = "choice"
version = "0.1.0"
edition = "2021"

[dependencies]
ttf = { path = "../ttf" }
anyhow = "1.0"
log = "0.4"
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
schemars = { version = "0.8", optional = true }
validator = "0.16"

[features]
serde-1 = ["serde", "serde_derive", "schemars"]
