[book]
authors = ["Lucas Javaudin"]
language = "en"
multilingual = false
src = "src"
title = "Metropolis Documentation"
description = "General documentation for the transport simulator Metropolis"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
curly-quotes = true
mathjax-support = true
